[package]
name = "bullet_hip_backend"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
bullet_core = { workspace = true }

[build-dependencies]
cc = "1.2.5"

[features]
hip = []
gh-actions = []

[[example]]
name = "mnist"
path = "../../examples/extra/mnist.rs"
